# Generated by Django 4.0.3 on 2022-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2017', 2017), ('2023', 2023), ('2019', 2019), ('2020', 2020), ('2015', 2015), ('2022', 2022), ('2021', 2021), ('2018', 2018), ('2016', 2016)], max_length=30),
        ),
    ]
