# Generated by Django 4.0.3 on 2022-03-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_alter_publicationsyears_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduceus',
            name='category',
            field=models.CharField(choices=[('Professor', 'Professor'), ('MS Students', 'MS Students'), ('Research Collaborators', 'Research Collaborators'), ('Research Professor', 'Research Professor'), ('Undergraduate', 'Undergraduate'), ('PhD Students', 'PhD Students')], default='Professor', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2018', 2018), ('2023', 2023), ('2019', 2019), ('2016', 2016), ('2020', 2020), ('2022', 2022), ('2017', 2017), ('2021', 2021), ('2015', 2015)], max_length=30, unique=True),
        ),
    ]
