# Generated by Django 4.0.3 on 2022-03-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0004_alter_introduceus_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduceus',
            name='category',
            field=models.CharField(choices=[('Research Collaborators', 'Research Collaborators'), ('Undergraduate', 'Undergraduate'), ('Professor', 'Professor'), ('Research Professor', 'Research Professor'), ('PhD Students', 'PhD Students'), ('MS Students', 'MS Students')], max_length=40),
        ),
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2020', 2020), ('2023', 2023), ('2018', 2018), ('2016', 2016), ('2022', 2022), ('2015', 2015), ('2017', 2017), ('2021', 2021), ('2019', 2019)], max_length=30, unique=True),
        ),
    ]
