# Generated by Django 4.0.3 on 2022-03-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0005_alter_introduceus_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostitle_photos',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='photostitle_photos',
            name='where',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='introduceus',
            name='category',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Research Collaborators', 'Research Collaborators'), ('Undergraduate', 'Undergraduate'), ('Research Professor', 'Research Professor'), ('MS Students', 'MS Students'), ('PhD Students', 'PhD Students')], max_length=40),
        ),
        migrations.AlterField(
            model_name='introduceus',
            name='image',
            field=models.ImageField(upload_to='indexpage'),
        ),
        migrations.AlterField(
            model_name='photostitle_photos',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='image',
            field=models.ImageField(upload_to='publications'),
        ),
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2019', 2019), ('2015', 2015), ('2017', 2017), ('2020', 2020), ('2023', 2023), ('2021', 2021), ('2018', 2018), ('2016', 2016), ('2022', 2022)], max_length=30, unique=True),
        ),
    ]
