# Generated by Django 4.0.3 on 2022-03-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0006_photostitle_photos_address_photostitle_photos_where_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduceus',
            name='category',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Research Collaborators', 'Research Collaborators'), ('Research Professor', 'Research Professor'), ('PhD Students', 'PhD Students'), ('MS Students', 'MS Students'), ('Professor', 'Professor')], max_length=40),
        ),
        migrations.AlterField(
            model_name='photostitle_photos',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='photostitle_photos',
            name='where',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2019', 2019), ('2016', 2016), ('2020', 2020), ('2023', 2023), ('2018', 2018), ('2017', 2017), ('2022', 2022), ('2021', 2021), ('2015', 2015)], max_length=30, unique=True),
        ),
    ]
