# Generated by Django 4.0.3 on 2022-03-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0007_alter_introduceus_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduceus',
            name='category',
            field=models.CharField(choices=[('MS Students', 'MS Students'), ('PhD Students', 'PhD Students'), ('Research Collaborators', 'Research Collaborators'), ('Undergraduate', 'Undergraduate'), ('Research Professor', 'Research Professor'), ('Professor', 'Professor')], max_length=40),
        ),
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2017', 2017), ('2022', 2022), ('2019', 2019), ('2020', 2020), ('2018', 2018), ('2016', 2016), ('2023', 2023), ('2015', 2015), ('2021', 2021)], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='WhatWeDoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatwedo', to='indexpage.whatwedo')),
            ],
        ),
    ]
