# Generated by Django 4.0.3 on 2022-03-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0008_alter_introduceus_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedodetail',
            name='img',
            field=models.ImageField(default='', upload_to='detailpic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='introduceus',
            name='category',
            field=models.CharField(choices=[('MS Students', 'MS Students'), ('Professor', 'Professor'), ('Undergraduate', 'Undergraduate'), ('Research Collaborators', 'Research Collaborators'), ('Research Professor', 'Research Professor'), ('PhD Students', 'PhD Students')], max_length=40),
        ),
        migrations.AlterField(
            model_name='publicationsyears',
            name='year',
            field=models.CharField(choices=[('2023', 2023), ('2021', 2021), ('2022', 2022), ('2016', 2016), ('2019', 2019), ('2015', 2015), ('2017', 2017), ('2020', 2020), ('2018', 2018)], max_length=30, unique=True),
        ),
    ]
